#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# added by Anaconda3 2019.03 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/woss/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/woss/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/woss/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/Users/woss/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

export GOPATH=$HOME/go
export PYTHON=/usr/bin/python2.7

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/woss/Projects/sensio.photo/sensio-faas/api/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/woss/Projects/sensio.photo/sensio-faas/api/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/woss/Projects/sensio.photo/sensio-faas/api/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/woss/Projects/sensio.photo/sensio-faas/api/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/woss/Projects/sensio.photo/sensio-faas/api/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/woss/Projects/sensio.photo/sensio-faas/api/node_modules/tabtab/.completions/slss.zsh
export VOLTA_HOME="$HOME/.volta"
[ -s "$VOLTA_HOME/load.sh" ] && . "$VOLTA_HOME/load.sh"

export PATH="$VOLTA_HOME/bin:$PATH"
