#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file

autoload -Uz promptinit
promptinit
prompt garrett

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export ANDROID_HOME=/usr/local/Caskroom/android-sdk/25.2.3/
export ANDROID_SDK_ROOT=$ANDROID_HOME

autoload -U add-zsh-hook
load-nvmrc() {
if [[ -f .nvmrc && -r .nvmrc ]]; then
  nvm use
fi
}

load-conda() {
if [[ -f .virtualenv && -r .virtualenv ]]; then
    echo "loading virtual env"
    source activate $(cat .virtualenv)
fi
}

add-zsh-hook chpwd load-nvmrc
add-zsh-hook chpwd load-conda

export PATH="$HOME/anaconda3/bin:$PATH"
export PATH="$PATH:/usr/local/Caskroom/android-sdk/25.2.3/emulator:/usr/local/Caskroom/android-sdk/25.2.3/tools/bin"
export PATH="$PATH:`yarn global bin`"
export LDFLAGS="/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then source "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then source "$HOME/google-cloud-sdk/completion.zsh.inc"; fi
source <(kubectl completion zsh)
export VISUAL=nvim
export EDITOR="$VISUAL"
alias kctl="kubectl"
